In [2]:
import pandas as pd
winefile = pd.read_csv('C:/Users\Windows/Documents/machine_learning_winedataset/wine_dataset.csv')

In [22]:
winefile

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [4]:
winefile['style'] = winefile['style'].replace('red', 0)

In [5]:
winefile['style'] = winefile['style'].replace('white', 1)

In [6]:
winefile

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [7]:
#separete variable between predictores and target
y = winefile['style']
x = winefile.drop('style', axis = 1)

In [8]:
from sklearn.model_selection import train_test_split

#create data for train and test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [13]:
from sklearn.ensemble import ExtraTreesClassifier
#Model criation;
model = ExtraTreesClassifier(n_estimators=100)
model.fit(x_train,y_train)

#print results
result = model.score(x_test, y_test)
print("Accuracy:", result)

Accuracy: 0.9938461538461538

In [33]:
y_test[400:411]

20      0
3834    1
2669    1
6249    1
4589    1
3823    1
3250    1
4413    1
2222    1
2125    1
4956    1
Name: style, dtype: int64

In [32]:
x_test[400:411]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
20,8.9,0.220,0.48,1.8,0.077,29.0,60.0,0.99680,3.39,0.53,9.4,6
3834,6.9,0.440,0.42,8.5,0.048,10.0,147.0,0.99740,3.32,0.46,9.5,6
2669,8.0,0.370,0.32,1.6,0.040,32.0,166.0,0.99200,3.00,0.55,11.3,7
6249,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,5
4589,5.0,0.270,0.32,4.5,0.032,58.0,178.0,0.98956,3.45,0.31,12.6,7
3823,8.0,0.450,0.28,10.8,0.051,25.0,157.0,0.99570,3.06,0.47,11.4,7
3250,6.4,0.420,0.74,12.8,0.076,48.0,209.0,0.99780,3.12,0.58,9.0,6
4413,6.7,0.190,0.39,1.0,0.032,14.0,71.0,0.98912,3.31,0.38,13.0,7
2222,7.2,0.240,0.34,1.1,0.045,3.0,64.0,0.99130,3.23,0.51,11.4,5
2125,7.2,0.310,0.46,5.0,0.040,3.0,29.0,0.99060,3.04,0.53,12.5,4
4956,6.0,0.220,0.33,12.2,0.033,25.0,97.0,0.99356,3.17,0.42,11.3,7

In [34]:
predict = model.predict(x_test[400:411])

In [35]:
predict

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)